FROM ubuntu:14.04
MAINTAINER org.apache.griffin

#install wget, ssh, unzip
RUN apt-get update && apt-get install wget -y
RUN mkdir /apache 
WORKDIR /apache
ADD prep /apache

EXPOSE 2122

#software install
RUN ./software-install.sh

ENV JAVA_HOME /apache/jdk
ENV SCALA_HOME /apache/scala
ENV KAFKA_HOME /apache/kafka

ENV PATH $JAVA_HOME/bin:$PATH:$SCALA_HOME/bin:$KAFKA_HOME/bin

EXPOSE 2181 9092

ADD bootstrap.sh /etc
RUN chmod 755 /etc/bootstrap.sh

ENTRYPOINT ["/etc/bootstrap.sh"]
